<?php
/**
 * @file
 * Add the tarteaucitron.js service.
 */

/**
 * Implements hook_page_attachments().
 */
function tarteocitron_page_attachments(&$attachments) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  $config = \Drupal::config('tarteocitron.settings');

  $settings['config'] = [
    'cdn' => '/libraries/tarteaucitron.js/',
    'language' => \Drupal::languageManager()->getCurrentLanguage()->getId(),
    'adblocker' => $config->get('tarteocitron_adblocker'),
    'hashtag' => $config->get('tarteocitron_hashtag'),
    'cookiename' => $config->get('tarteocitron_cookiename'),
    'highprivacy' => $config->get('tarteocitron_highprivacy'),
    'orientation' => $config->get('tarteocitron_orientation'),
    'bodyposition' => $config->get('tarteocitron_bodyposition'),
    'removecredit' => $config->get('tarteocitron_removecredit'),
    'showalertsmall' => $config->get('tarteocitron_showalertsmall'),
    'showdetailsonclick' => $config->get('tarteocitron_showdetailsonclick'),
    'showicon' => $config->get('tarteocitron_showicon'),
    'iconposition' => $config->get('tarteocitron_iconposition'),
    'cookieslist' => $config->get('tarteocitron_cookieslist'),
    'cookieslistembed' => $config->get('tarteocitron_cookieslistembed'),
    'handlebrowserdntrequest' => $config->get('tarteocitron_handlebrowserdntrequest'),
    'denyallcta' => $config->get('tarteocitron_denyallcta'),
    'acceptallcta' => $config->get('tarteocitron_acceptallcta'),
    'moreinfolink' => $config->get('tarteocitron_moreinfolink'),
    'privacyurl' => $config->get('tarteocitron_privacyurl'),
    'useexternalcss' => $config->get('tarteocitron_useexternalcss'),
    'useexternaljs' => $config->get('tarteocitron_useexternaljs'),
    'mandatory' => $config->get('tarteocitron_mandatory'),
    'mandatorycta' => $config->get('tarteocitron_mandatorycta'),
    'closepopup' => $config->get('tarteocitron_closepopup'),
    'groupServices' => $config->get('tarteocitron_groupservices'),
    'servicedefaultstate' => $config->get('tarteocitron_servicedefaultstate'),
    'googleconsentmode' => $config->get('tarteocitron_googleconsentmode'),
    'bingconsentmode' => $config->get('tarteocitron_bingconsentmode'),
    'softconsentmode' => $config->get('tarteocitron_softconsentmode'),
    'datalayer' => $config->get('tarteocitron_datalayer'),
    'serverside' => $config->get('tarteocitron_serverside'),
    'partnerslist' => $config->get('tarteocitron_partnerslist'),
    'alwaysneedconsent' => $config->get('tarteocitron_alwaysneedconsent'),
    'readmorelink' => $config->get('tarteocitron_readmorelink'),
    'custom_text' => $config->get('tarteocitron_customtext'),
    'services' => $config->get('tarteocitron_services'),
  ];

  $attachments['#attached']['library'][] = 'tarteocitron/libraries.tarteaucitron';
  $attachments['#attached']['library'][] = 'tarteocitron/tarteocitron.services';
  $attachments['#attached']['library'][] = 'tarteocitron/tarteocitron.init';
  $attachments['#attached']['drupalSettings']['tarteocitron'] = $settings;
}
